obj = {'data': [
    {u'requires_post_code': False, u'code': u'AF', u'name': u'Afghanistan', u'phone_code': None, u'enabled': True,
     u'slug': u'afghanistan'},
    {u'requires_post_code': False, u'code': u'BS', u'name': u'Bahamas', u'phone_code': None, u'enabled': True,
     u'slug': u'bahamas'},
    {u'requires_post_code': False, u'code': u'BH', u'name': u'Bahrain', u'phone_code': None, u'enabled': True,
     u'slug': u'bahrain'},
    {u'requires_post_code': True, u'code': u'BD', u'name': u'Bangladesh', u'phone_code': None, u'enabled': True,
     u'slug': u'bangladesh'},
    {u'requires_post_code': False, u'code': u'BB', u'name': u'Barbados', u'phone_code': None, u'enabled': True,
     u'slug': u'barbados'},
    {u'requires_post_code': True, u'code': u'BY', u'name': u'Belarus', u'phone_code': None, u'enabled': True,
     u'slug': u'belarus'},
    {u'requires_post_code': True, u'code': u'BE', u'name': u'Belgium', u'phone_code': None, u'enabled': True,
     u'slug': u'belgium'},
    {u'requires_post_code': False, u'code': u'BZ', u'name': u'Belize', u'phone_code': None, u'enabled': True,
     u'slug': u'belize'},
    {u'requires_post_code': False, u'code': u'JT', u'name': u'Johnston Island', u'phone_code': None, u'enabled': False,
     u'slug': u'johnston-island'},
    {u'requires_post_code': False, u'code': u'BJ', u'name': u'Benin', u'phone_code': None, u'enabled': True,
     u'slug': u'benin'},
    {u'requires_post_code': False, u'code': u'BM', u'name': u'Bermuda', u'phone_code': None, u'enabled': True,
     u'slug': u'bermuda'},
    {u'requires_post_code': False, u'code': u'BT', u'name': u'Bhutan', u'phone_code': None, u'enabled': True,
     u'slug': u'bhutan'},
    {u'requires_post_code': False, u'code': u'BO', u'name': u'Bolivia', u'phone_code': None, u'enabled': True,
     u'slug': u'bolivia'},
    {u'requires_post_code': False, u'code': u'BW', u'name': u'Botswana', u'phone_code': None, u'enabled': True,
     u'slug': u'botswana'},
    {u'requires_post_code': False, u'code': u'BI', u'name': u'Burundi', u'phone_code': None, u'enabled': True,
     u'slug': u'burundi'},
    {u'requires_post_code': True, u'code': u'HR', u'name': u'Croatia', u'phone_code': None, u'enabled': True,
     u'slug': u'croatia'},
    {u'requires_post_code': False, u'code': u'EC', u'name': u'Ecuador', u'phone_code': None, u'enabled': True,
     u'slug': u'ecuador'},
    {u'requires_post_code': False, u'code': u'EG', u'name': u'Egypt', u'phone_code': None, u'enabled': True,
     u'slug': u'egypt'},
    {u'requires_post_code': False, u'code': u'ER', u'name': u'Eritrea', u'phone_code': None, u'enabled': True,
     u'slug': u'eritrea'},
    {u'requires_post_code': True, u'code': u'EE', u'name': u'Estonia', u'phone_code': None, u'enabled': True,
     u'slug': u'estonia'},
    {u'requires_post_code': False, u'code': u'ET', u'name': u'Ethiopia', u'phone_code': None, u'enabled': True,
     u'slug': u'ethiopia'},
    {u'requires_post_code': False, u'code': u'GA', u'name': u'Gabon', u'phone_code': None, u'enabled': True,
     u'slug': u'gabon'},
    {u'requires_post_code': False, u'code': u'GM', u'name': u'Gambia', u'phone_code': None, u'enabled': True,
     u'slug': u'gambia'},
    {u'requires_post_code': False, u'code': u'GH', u'name': u'Ghana', u'phone_code': None, u'enabled': True,
     u'slug': u'ghana'},
    {u'requires_post_code': False, u'code': u'WK', u'name': u'Wake Island', u'phone_code': None, u'enabled': False,
     u'slug': u'wake-island'},
    {u'requires_post_code': False, u'code': u'GI', u'name': u'Gibraltar', u'phone_code': None, u'enabled': True,
     u'slug': u'gibraltar'},
    {u'requires_post_code': False, u'code': u'GR', u'name': u'Greece', u'phone_code': None, u'enabled': False,
     u'slug': u'greece'},
    {u'requires_post_code': True, u'code': u'GL', u'name': u'Greenland', u'phone_code': None, u'enabled': True,
     u'slug': u'greenland'},
    {u'requires_post_code': False, u'code': u'GD', u'name': u'Grenada', u'phone_code': None, u'enabled': True,
     u'slug': u'grenada'},
    {u'requires_post_code': False, u'code': u'PC', u'name': u'Pacific Islands Trust Territory', u'phone_code': None,
     u'enabled': False, u'slug': u'pacific-islands-trust-territory'},
    {u'requires_post_code': True, u'code': u'GP', u'name': u'Guadeloupe', u'phone_code': None, u'enabled': True,
     u'slug': u'guadeloupe'},
    {u'requires_post_code': True, u'code': u'GU', u'name': u'Guam', u'phone_code': None, u'enabled': True,
     u'slug': u'guam'},
    {u'requires_post_code': False, u'code': u'GT', u'name': u'Guatemala', u'phone_code': None, u'enabled': True,
     u'slug': u'guatemala'},
    {u'requires_post_code': True, u'code': u'GG', u'name': u'Guernsey', u'phone_code': None, u'enabled': True,
     u'slug': u'guernsey'},
    {u'requires_post_code': False, u'code': u'GN', u'name': u'Guinea Republic', u'phone_code': None, u'enabled': True,
     u'slug': u'guinea'},
    {u'requires_post_code': False, u'code': u'GW', u'name': u'Guinea-Bissau', u'phone_code': None, u'enabled': True,
     u'slug': u'guinea-bissau'},
    {u'requires_post_code': False, u'code': u'GY', u'name': u'Guyana (British)', u'phone_code': None, u'enabled': True,
     u'slug': u'guyana'},
    {u'requires_post_code': False, u'code': u'HT', u'name': u'Haiti', u'phone_code': None, u'enabled': True,
     u'slug': u'haiti'},
    {u'requires_post_code': False, u'code': u'HN', u'name': u'Honduras', u'phone_code': None, u'enabled': True,
     u'slug': u'honduras'},
    {u'requires_post_code': False, u'code': u'HK', u'name': u'Hong Kong', u'phone_code': None, u'enabled': True,
     u'slug': u'hong-kong-sar-china'},
    {u'requires_post_code': True, u'code': u'HU', u'name': u'Hungary', u'phone_code': None, u'enabled': True,
     u'slug': u'hungary'},
    {u'requires_post_code': False, u'code': u'IQ', u'name': u'Iraq', u'phone_code': None, u'enabled': True,
     u'slug': u'iraq'},
    {u'requires_post_code': False, u'code': u'JM', u'name': u'Jamaica', u'phone_code': None, u'enabled': True,
     u'slug': u'jamaica'},
    {u'requires_post_code': True, u'code': u'JP', u'name': u'Japan', u'phone_code': None, u'enabled': True,
     u'slug': u'japan'},
    {u'requires_post_code': True, u'code': u'JE', u'name': u'Jersey', u'phone_code': None, u'enabled': True,
     u'slug': u'jersey'},
    {u'requires_post_code': True, u'code': u'TJ', u'name': u'Tajikistan', u'phone_code': None, u'enabled': True,
     u'slug': u'tajikistan'},
    {u'requires_post_code': True, u'code': u'TH', u'name': u'Thailand', u'phone_code': None, u'enabled': True,
     u'slug': u'thailand'},
    {u'requires_post_code': False, u'code': u'TL', u'name': u'Timor Leste', u'phone_code': None, u'enabled': True,
     u'slug': u'timor-leste'},
    {u'requires_post_code': True, u'code': u'TN', u'name': u'Tunisia', u'phone_code': None, u'enabled': True,
     u'slug': u'tunisia'},
    {u'requires_post_code': False, u'code': u'TM', u'name': u'Turkmenistan', u'phone_code': None, u'enabled': True,
     u'slug': u'turkmenistan'},
    {u'requires_post_code': True, u'code': u'UZ', u'name': u'Uzbekistan', u'phone_code': None, u'enabled': True,
     u'slug': u'uzbekistan'},
    {u'requires_post_code': False, u'code': u'VE', u'name': u'Venezuela', u'phone_code': None, u'enabled': True,
     u'slug': u'venezuela'},
    {u'requires_post_code': False, u'code': u'VN', u'name': u'Vietnam', u'phone_code': None, u'enabled': True,
     u'slug': u'vietnam'},
    {u'requires_post_code': False, u'code': u'ZM', u'name': u'Zambia', u'phone_code': None, u'enabled': True,
     u'slug': u'zambia'},
    {u'requires_post_code': False, u'code': u'SU', u'name': u'Union of Soviet Socialist Republics', u'phone_code': None,
     u'enabled': False, u'slug': u'union-of-soviet-socialist-republics'},
    {u'requires_post_code': False, u'code': u'PZ', u'name': u'Panama Canal Zone', u'phone_code': None, u'enabled': False,
     u'slug': u'panama-canal-zone'},
    {u'requires_post_code': False, u'code': u'ZZ', u'name': u'Unknown or Invalid Region', u'phone_code': None,
     u'enabled': False, u'slug': u'unknown-or-invalid-region'},
    {u'requires_post_code': False, u'code': u'JO', u'name': u'Jordan', u'phone_code': None, u'enabled': True,
     u'slug': u'jordan'},
    {u'requires_post_code': True, u'code': u'MG', u'name': u'Madagascar', u'phone_code': None, u'enabled': True,
     u'slug': u'madagascar'},
    {u'requires_post_code': True, u'code': u'MD', u'name': u'Moldova, Republic Of', u'phone_code': None,
     u'enabled': True, u'slug': u'moldova'},
    {u'requires_post_code': True, u'code': u'MC', u'name': u'Monaco', u'phone_code': None, u'enabled': True,
     u'slug': u'monaco'},
    {u'requires_post_code': True, u'code': u'ME', u'name': u'Montenegro, Republic Of', u'phone_code': None,
     u'enabled': True, u'slug': u'montenegro'},
    {u'requires_post_code': False, u'code': u'MM', u'name': u'Myanmar', u'phone_code': None, u'enabled': True,
     u'slug': u'myanmar-burma'},
    {u'requires_post_code': False, u'code': u'NG', u'name': u'Nigeria', u'phone_code': None, u'enabled': True,
     u'slug': u'nigeria'},
    {u'requires_post_code': False, u'code': u'OM', u'name': u'Oman', u'phone_code': None, u'enabled': True,
     u'slug': u'oman'},
    {u'requires_post_code': True, u'code': u'PK', u'name': u'Pakistan', u'phone_code': None, u'enabled': True,
     u'slug': u'pakistan'},
    {u'requires_post_code': True, u'code': u'PW', u'name': u'Palau', u'phone_code': None, u'enabled': True,
     u'slug': u'palau'},
    {u'requires_post_code': False, u'code': u'BV', u'name': u'Bouvet Island', u'phone_code': None, u'enabled': True,
     u'slug': u'bouvet-island'},
    {u'requires_post_code': False, u'code': u'PA', u'name': u'Panama', u'phone_code': None, u'enabled': True,
     u'slug': u'panama'},
    {u'requires_post_code': True, u'code': u'PG', u'name': u'Papua New Guinea', u'phone_code': None, u'enabled': True,
     u'slug': u'papua-new-guinea'},
    {u'requires_post_code': False, u'code': u'WS', u'name': u'Samoa', u'phone_code': None, u'enabled': True,
     u'slug': u'samoa'},
    {u'requires_post_code': False, u'code': u'SB', u'name': u'Solomon Islands', u'phone_code': None, u'enabled': True,
     u'slug': u'solomon-islands'},
    {u'requires_post_code': False, u'code': u'SO', u'name': u'Somalia', u'phone_code': None, u'enabled': True,
     u'slug': u'somalia'},
    {u'requires_post_code': True, u'code': u'ZA', u'name': u'South Africa', u'phone_code': None, u'enabled': True,
     u'slug': u'south-africa'},
    {u'requires_post_code': True, u'code': u'ES', u'name': u'Spain', u'phone_code': None, u'enabled': True,
     u'slug': u'spain'},
    {u'requires_post_code': False, u'code': u'GS', u'name': u'South Georgia and the South Sandwich Islands',
     u'phone_code': None, u'enabled': True, u'slug': u'south-georgia-and-the-south-sandwich-islands'},
    {u'requires_post_code': False, u'code': u'MF', u'name': u'Saint Martin', u'phone_code': None, u'enabled': True,
     u'slug': u'saint-martin'},
    {u'requires_post_code': False, u'code': u'PN', u'name': u'Pitcairn Islands', u'phone_code': None, u'enabled': True,
     u'slug': u'pitcairn-islands'},
    {u'requires_post_code': False, u'code': u'PS', u'name': u'Palestinian Territories', u'phone_code': None,
     u'enabled': True, u'slug': u'palestinian-territories'},
    {u'requires_post_code': False, u'code': u'TK', u'name': u'Tokelau', u'phone_code': None, u'enabled': True,
     u'slug': u'tokelau'},
    {u'requires_post_code': False, u'code': u'WF', u'name': u'Wallis and Futuna', u'phone_code': None, u'enabled': True,
     u'slug': u'wallis-and-futuna'},
    {u'requires_post_code': True, u'code': u'DZ', u'name': u'Algeria', u'phone_code': None, u'enabled': True,
     u'slug': u'algeria'},
    {u'requires_post_code': False, u'code': u'AW', u'name': u'Aruba', u'phone_code': None, u'enabled': True,
     u'slug': u'aruba'},
    {u'requires_post_code': True, u'code': u'BG', u'name': u'Bulgaria', u'phone_code': None, u'enabled': True,
     u'slug': u'bulgaria'},
    {u'requires_post_code': False, u'code': u'MI', u'name': u'Midway Islands', u'phone_code': None, u'enabled': False,
     u'slug': u'midway-islands'},
    {u'requires_post_code': False, u'code': u'BF', u'name': u'Burkina Faso', u'phone_code': None, u'enabled': True,
     u'slug': u'burkina-faso'},
    {u'requires_post_code': True, u'code': u'CA', u'name': u'Canada', u'phone_code': None, u'enabled': True,
     u'slug': u'canada'},
    {u'requires_post_code': False, u'code': u'CV', u'name': u'Cape Verde', u'phone_code': None, u'enabled': True,
     u'slug': u'cape-verde'},
    {u'requires_post_code': False, u'code': u'KY', u'name': u'Cayman Islands', u'phone_code': None, u'enabled': True,
     u'slug': u'cayman-islands'},
    {u'requires_post_code': False, u'code': u'CF', u'name': u'Central African Republic', u'phone_code': None,
     u'enabled': True, u'slug': u'central-african-republic'},
    {u'requires_post_code': False, u'code': u'CL', u'name': u'Chile', u'phone_code': None, u'enabled': True,
     u'slug': u'chile'},
    {u'requires_post_code': True, u'code': u'CN', u'name': u'China, Peoples Republic', u'phone_code': None,
     u'enabled': True, u'slug': u'china'},
    {u'requires_post_code': False, u'code': u'CO', u'name': u'Colombia', u'phone_code': None, u'enabled': True,
     u'slug': u'colombia'},
    {u'requires_post_code': False, u'code': u'CG', u'name': u'Congo', u'phone_code': None, u'enabled': True,
     u'slug': u'congo-brazzaville'},
    {u'requires_post_code': False, u'code': u'CK', u'name': u'Cook Islands', u'phone_code': None, u'enabled': True,
     u'slug': u'cook-islands'},
    {u'requires_post_code': False, u'code': u'CI', u'name': u'Cote D Ivoire', u'phone_code': None, u'enabled': True,
     u'slug': u'cote-divoire'},
    {u'requires_post_code': True, u'code': u'FO', u'name': u'Faroe Islands', u'phone_code': None, u'enabled': True,
     u'slug': u'faroe-islands'},
    {u'requires_post_code': True, u'code': u'SE', u'name': u'Sweden', u'phone_code': None, u'enabled': True,
     u'slug': u'sweden'},
    {u'requires_post_code': False, u'code': u'FJ', u'name': u'Fiji', u'phone_code': None, u'enabled': True,
     u'slug': u'fiji'},
    {u'requires_post_code': True, u'code': u'FI', u'name': u'Finland', u'phone_code': None, u'enabled': True,
     u'slug': u'finland'},
    {u'requires_post_code': False, u'code': u'FQ', u'name': u'French Southern and Antarctic Territories',
     u'phone_code': None, u'enabled': False, u'slug': u'french-southern-and-antarctic-territories'},
    {u'requires_post_code': True, u'code': u'CH', u'name': u'Switzerland', u'phone_code': None, u'enabled': True,
     u'slug': u'switzerland'},
    {u'requires_post_code': True, u'code': u'FR', u'name': u'France', u'phone_code': None, u'enabled': True,
     u'slug': u'france'},
    {u'requires_post_code': False, u'code': u'FX', u'name': u'Metropolitan France', u'phone_code': None,
     u'enabled': False, u'slug': u'metropolitan-france'},
    {u'requires_post_code': True, u'code': u'IL', u'name': u'Israel', u'phone_code': None, u'enabled': True,
     u'slug': u'israel'},
    {u'requires_post_code': True, u'code': u'KZ', u'name': u'Kazakhstan', u'phone_code': None, u'enabled': True,
     u'slug': u'kazakhstan'},
    {u'requires_post_code': False, u'code': u'KE', u'name': u'Kenya', u'phone_code': None, u'enabled': True,
     u'slug': u'kenya'},
    {u'requires_post_code': False, u'code': u'KI', u'name': u'Kiribati', u'phone_code': None, u'enabled': True,
     u'slug': u'kiribati'},
    {u'requires_post_code': True, u'code': u'KR', u'name': u'Korea, Republic Of (South K.)', u'phone_code': None,
     u'enabled': True, u'slug': u'south-korea'},
    {u'requires_post_code': False, u'code': u'KP', u'name': u'Korea, The D.P.R Of (North K.)', u'phone_code': None,
     u'enabled': True, u'slug': u'north-korea'},
    {u'requires_post_code': False, u'code': u'KW', u'name': u'Kuwait', u'phone_code': None, u'enabled': True,
     u'slug': u'kuwait'},
    {u'requires_post_code': True, u'code': u'KG', u'name': u'Kyrgyzstan', u'phone_code': None, u'enabled': True,
     u'slug': u'kyrgyzstan'},
    {u'requires_post_code': False, u'code': u'LA', u'name': u'Lao Peoples Democratic Republic', u'phone_code': None,
     u'enabled': True, u'slug': u'laos'},
    {u'requires_post_code': True, u'code': u'MK', u'name': u'Macedonia, Republic Of', u'phone_code': None,
     u'enabled': True, u'slug': u'macedonia'},
    {u'requires_post_code': True, u'code': u'MY', u'name': u'Malaysia', u'phone_code': None, u'enabled': True,
     u'slug': u'malaysia'},
    {u'requires_post_code': True, u'code': u'MV', u'name': u'Maldives', u'phone_code': None, u'enabled': True,
     u'slug': u'maldives'},
    {u'requires_post_code': False, u'code': u'ML', u'name': u'Mali', u'phone_code': None, u'enabled': True,
     u'slug': u'mali'},
    {u'requires_post_code': False, u'code': u'MT', u'name': u'Malta', u'phone_code': None, u'enabled': True,
     u'slug': u'malta'},
    {u'requires_post_code': False, u'code': u'SY', u'name': u'Syria', u'phone_code': None, u'enabled': True,
     u'slug': u'syria'},
    {u'requires_post_code': False, u'code': u'TV', u'name': u'Tuvalu', u'phone_code': None, u'enabled': True,
     u'slug': u'tuvalu'},
    {u'requires_post_code': False, u'code': u'UG', u'name': u'Uganda', u'phone_code': None, u'enabled': True,
     u'slug': u'uganda'},
    {u'requires_post_code': False, u'code': u'UY', u'name': u'Uruguay', u'phone_code': None, u'enabled': True,
     u'slug': u'uruguay'},
    {u'requires_post_code': False, u'code': u'NQ', u'name': u'Dronning Maud Land', u'phone_code': None,
     u'enabled': False, u'slug': u'dronning-maud-land'},
    {u'requires_post_code': False, u'code': u'VU', u'name': u'Vanuatu', u'phone_code': None, u'enabled': True,
     u'slug': u'vanuatu'},
    {u'requires_post_code': False, u'code': u'NT', u'name': u'Neutral Zone', u'phone_code': None, u'enabled': False,
     u'slug': u'neutral-zone'},
    {u'requires_post_code': False, u'code': u'YE', u'name': u'Yemen, Republic Of', u'phone_code': None, u'enabled': True,
     u'slug': u'yemen'},
    {u'requires_post_code': False, u'code': u'CS', u'name': u'Serbia and Montenegro', u'phone_code': None,
     u'enabled': False, u'slug': u'serbia-and-montenegro'},
    {u'requires_post_code': False, u'code': u'CT', u'name': u'Canton and Enderbury Islands', u'phone_code': None,
     u'enabled': False, u'slug': u'canton-and-enderbury-islands'},
    {u'requires_post_code': False, u'code': u'DD', u'name': u'East Germany', u'phone_code': None, u'enabled': False,
     u'slug': u'east-germany'},
    {u'requires_post_code': False, u'code': u'YD', u'name': u"People's Democratic Republic of Yemen",
     u'phone_code': None, u'enabled': False, u'slug': u'people-s-democratic-republic-of-yemen'},
    {u'requires_post_code': True, u'code': u'MH', u'name': u'Marshall Islands', u'phone_code': None, u'enabled': True,
     u'slug': u'marshall-islands'},
    {u'requires_post_code': False, u'code': u'AX', u'name': u'\xc5land Islands', u'phone_code': None, u'enabled': True,
     u'slug': u'aland-islands'},
    {u'requires_post_code': True, u'code': u'MQ', u'name': u'Martinique', u'phone_code': None, u'enabled': True,
     u'slug': u'martinique'},
    {u'requires_post_code': False, u'code': u'MR', u'name': u'Mauritania', u'phone_code': None, u'enabled': True,
     u'slug': u'mauritania'},
    {u'requires_post_code': False, u'code': u'MU', u'name': u'Mauritius', u'phone_code': None, u'enabled': True,
     u'slug': u'mauritius'},
    {u'requires_post_code': True, u'code': u'MX', u'name': u'Mexico', u'phone_code': None, u'enabled': True,
     u'slug': u'mexico'},
    {u'requires_post_code': True, u'code': u'MN', u'name': u'Mongolia', u'phone_code': None, u'enabled': True,
     u'slug': u'mongolia'},
    {u'requires_post_code': False, u'code': u'MS', u'name': u'Montserrat', u'phone_code': None, u'enabled': True,
     u'slug': u'montserrat'},
    {u'requires_post_code': False, u'code': u'NA', u'name': u'Namibia', u'phone_code': None, u'enabled': True,
     u'slug': u'namibia'},
    {u'requires_post_code': False, u'code': u'NR', u'name': u'Nauru, Republic Of', u'phone_code': None, u'enabled': True,
     u'slug': u'nauru'},
    {u'requires_post_code': False, u'code': u'NP', u'name': u'Nepal', u'phone_code': None, u'enabled': True,
     u'slug': u'nepal'},
    {u'requires_post_code': False, u'code': u'CX', u'name': u'Christmas Island', u'phone_code': None, u'enabled': True,
     u'slug': u'christmas-island'},
    {u'requires_post_code': True, u'code': u'NL', u'name': u'Netherlands, The', u'phone_code': None, u'enabled': True,
     u'slug': u'netherlands'},
    {u'requires_post_code': True, u'code': u'NC', u'name': u'New Caledonia', u'phone_code': None, u'enabled': True,
     u'slug': u'new-caledonia'},
    {u'requires_post_code': True, u'code': u'NZ', u'name': u'New Zealand', u'phone_code': None, u'enabled': True,
     u'slug': u'new-zealand'},
    {u'requires_post_code': False, u'code': u'NI', u'name': u'Nicaragua', u'phone_code': None, u'enabled': True,
     u'slug': u'nicaragua'},
    {u'requires_post_code': False, u'code': u'NE', u'name': u'Niger', u'phone_code': None, u'enabled': True,
     u'slug': u'niger'},
    {u'requires_post_code': False, u'code': u'NU', u'name': u'Niue', u'phone_code': None, u'enabled': True,
     u'slug': u'niue'},
    {u'requires_post_code': True, u'code': u'NO', u'name': u'Norway', u'phone_code': None, u'enabled': True,
     u'slug': u'norway'},
    {u'requires_post_code': False, u'code': u'PY', u'name': u'Paraguay', u'phone_code': None, u'enabled': True,
     u'slug': u'paraguay'},
    {u'requires_post_code': False, u'code': u'SH', u'name': u'Saint Helena', u'phone_code': None, u'enabled': True,
     u'slug': u'saint-helena'},
    {u'requires_post_code': True, u'code': u'SM', u'name': u'San Marino', u'phone_code': None, u'enabled': True,
     u'slug': u'san-marino'},
    {u'requires_post_code': False, u'code': u'SN', u'name': u'Senegal', u'phone_code': None, u'enabled': True,
     u'slug': u'senegal'},
    {u'requires_post_code': False, u'code': u'IM', u'name': u'Isle of Man', u'phone_code': None, u'enabled': True,
     u'slug': u'isle-of-man'},
    {u'requires_post_code': False, u'code': u'SL', u'name': u'Sierra Leone', u'phone_code': None, u'enabled': True,
     u'slug': u'sierra-leone'},
    {u'requires_post_code': True, u'code': u'SG', u'name': u'Singapore', u'phone_code': None, u'enabled': True,
     u'slug': u'singapore'},
    {u'requires_post_code': True, u'code': u'SK', u'name': u'Slovakia', u'phone_code': None, u'enabled': True,
     u'slug': u'slovakia'},
    {u'requires_post_code': True, u'code': u'SI', u'name': u'Slovenia', u'phone_code': None, u'enabled': True,
     u'slug': u'slovenia'},
    {u'requires_post_code': False, u'code': u'LC', u'name': u'St. Lucia', u'phone_code': None, u'enabled': True,
     u'slug': u'saint-lucia'},
    {u'requires_post_code': False, u'code': u'SD', u'name': u'Sudan', u'phone_code': None, u'enabled': True,
     u'slug': u'sudan'},
    {u'requires_post_code': False, u'code': u'SR', u'name': u'Suriname', u'phone_code': None, u'enabled': True,
     u'slug': u'suriname'},
    {u'requires_post_code': True, u'code': u'SZ', u'name': u'Swaziland', u'phone_code': None, u'enabled': True,
     u'slug': u'swaziland'},
    {u'requires_post_code': False, u'code': u'UM', u'name': u'U.S. Minor Outlying Islands', u'phone_code': None,
     u'enabled': True, u'slug': u'u-s-minor-outlying-islands'},
    {u'requires_post_code': False, u'code': u'AL', u'name': u'Albania', u'phone_code': None, u'enabled': True,
     u'slug': u'albania'},
    {u'requires_post_code': True, u'code': u'AS', u'name': u'American Samoa', u'phone_code': None, u'enabled': True,
     u'slug': u'american-samoa'},
    {u'requires_post_code': True, u'code': u'AD', u'name': u'Andorra', u'phone_code': None, u'enabled': True,
     u'slug': u'andorra'},
    {u'requires_post_code': False, u'code': u'AO', u'name': u'Angola', u'phone_code': None, u'enabled': True,
     u'slug': u'angola'},
    {u'requires_post_code': False, u'code': u'AI', u'name': u'Anguilla', u'phone_code': None, u'enabled': True,
     u'slug': u'anguilla'},
    {u'requires_post_code': False, u'code': u'AG', u'name': u'Antigua', u'phone_code': None, u'enabled': True,
     u'slug': u'antigua-and-barbuda'},
    {u'requires_post_code': True, u'code': u'AR', u'name': u'Argentina', u'phone_code': None, u'enabled': True,
     u'slug': u'argentina'},
    {u'requires_post_code': True, u'code': u'AM', u'name': u'Armenia', u'phone_code': None, u'enabled': True,
     u'slug': u'armenia'},
    {u'requires_post_code': True, u'code': u'AU', u'name': u'Australia', u'phone_code': None, u'enabled': True,
     u'slug': u'australia'},
    {u'requires_post_code': True, u'code': u'AT', u'name': u'Austria', u'phone_code': None, u'enabled': True,
     u'slug': u'austria'},
    {u'requires_post_code': True, u'code': u'AZ', u'name': u'Azerbaijan', u'phone_code': None, u'enabled': True,
     u'slug': u'azerbaijan'},
    {u'requires_post_code': True, u'code': u'BA', u'name': u'Bosnia And Herzegovina', u'phone_code': None,
     u'enabled': True, u'slug': u'bosnia-and-herzegovina'},
    {u'requires_post_code': True, u'code': u'BR', u'name': u'Brazil', u'phone_code': None, u'enabled': True,
     u'slug': u'brazil'},
    {u'requires_post_code': True, u'code': u'BN', u'name': u'Brunei', u'phone_code': None, u'enabled': True,
     u'slug': u'brunei'},
    {u'requires_post_code': False, u'code': u'TD', u'name': u'Chad', u'phone_code': None, u'enabled': True,
     u'slug': u'chad'},
    {u'requires_post_code': True, u'code': u'MP', u'name': u'Commonwealth No. Mariana Islands', u'phone_code': None,
     u'enabled': True, u'slug': u'northern-mariana-islands'},
    {u'requires_post_code': False, u'code': u'KM', u'name': u'Comoros', u'phone_code': None, u'enabled': True,
     u'slug': u'comoros'},
    {u'requires_post_code': False, u'code': u'CD', u'name': u'Congo, The Democratic Republic Of', u'phone_code': None,
     u'enabled': True, u'slug': u'congo-kinshasa'},
    {u'requires_post_code': False, u'code': u'VD', u'name': u'North Vietnam', u'phone_code': None, u'enabled': False,
     u'slug': u'north-vietnam'},
    {u'requires_post_code': False, u'code': u'CR', u'name': u'Costa Rica', u'phone_code': None, u'enabled': True,
     u'slug': u'costa-rica'},
    {u'requires_post_code': False, u'code': u'FK', u'name': u'Falkland Islands', u'phone_code': None, u'enabled': True,
     u'slug': u'falkland-islands'},
    {u'requires_post_code': True, u'code': u'GF', u'name': u'French Guyana', u'phone_code': None, u'enabled': True,
     u'slug': u'french-guiana'},
    {u'requires_post_code': True, u'code': u'GE', u'name': u'Georgia', u'phone_code': None, u'enabled': True,
     u'slug': u'georgia'},
    {u'requires_post_code': True, u'code': u'DE', u'name': u'Germany', u'phone_code': None, u'enabled': True,
     u'slug': u'germany'},
    {u'requires_post_code': False, u'code': u'GQ', u'name': u'Guinea-Equatorial', u'phone_code': None, u'enabled': True,
     u'slug': u'equatorial-guinea'},
    {u'requires_post_code': True, u'code': u'IS', u'name': u'Iceland', u'phone_code': None, u'enabled': True,
     u'slug': u'iceland'},
    {u'requires_post_code': True, u'code': u'IN', u'name': u'India', u'phone_code': None, u'enabled': True,
     u'slug': u'india'},
    {u'requires_post_code': True, u'code': u'ID', u'name': u'Indonesia', u'phone_code': None, u'enabled': True,
     u'slug': u'indonesia'},
    {u'requires_post_code': False, u'code': u'IR', u'name': u'Iran (Islamic Republic Of)', u'phone_code': None,
     u'enabled': True, u'slug': u'iran'},
    {u'requires_post_code': True, u'code': u'IE', u'name': u'Ireland, Republic Of', u'phone_code': None,
     u'enabled': True, u'slug': u'ireland'},
    {u'requires_post_code': True, u'code': u'IT', u'name': u'Italy', u'phone_code': None, u'enabled': True,
     u'slug': u'italy'},
    {u'requires_post_code': True, u'code': u'LV', u'name': u'Latvia', u'phone_code': None, u'enabled': True,
     u'slug': u'latvia'},
    {u'requires_post_code': False, u'code': u'LB', u'name': u'Lebanon', u'phone_code': None, u'enabled': True,
     u'slug': u'lebanon'},
    {u'requires_post_code': False, u'code': u'LS', u'name': u'Lesotho', u'phone_code': None, u'enabled': True,
     u'slug': u'lesotho'},
    {u'requires_post_code': False, u'code': u'LR', u'name': u'Liberia', u'phone_code': None, u'enabled': True,
     u'slug': u'liberia'},
    {u'requires_post_code': False, u'code': u'LY', u'name': u'Libya', u'phone_code': None, u'enabled': True,
     u'slug': u'libya'},
    {u'requires_post_code': True, u'code': u'LI', u'name': u'Liechtenstein', u'phone_code': None, u'enabled': True,
     u'slug': u'liechtenstein'},
    {u'requires_post_code': False, u'code': u'PF', u'name': u'Tahiti', u'phone_code': None, u'enabled': True,
     u'slug': u'french-polynesia'},
    {u'requires_post_code': True, u'code': u'TW', u'name': u'Taiwan', u'phone_code': None, u'enabled': True,
     u'slug': u'taiwan'},
    {u'requires_post_code': False, u'code': u'TZ', u'name': u'Tanzania', u'phone_code': None, u'enabled': True,
     u'slug': u'tanzania'},
    {u'requires_post_code': False, u'code': u'TG', u'name': u'Togo', u'phone_code': None, u'enabled': True,
     u'slug': u'togo'},
    {u'requires_post_code': False, u'code': u'TO', u'name': u'Tonga', u'phone_code': None, u'enabled': True,
     u'slug': u'tonga'},
    {u'requires_post_code': False, u'code': u'PU', u'name': u'U.S. Miscellaneous Pacific Islands', u'phone_code': None,
     u'enabled': False, u'slug': u'u-s-miscellaneous-pacific-islands'},
    {u'requires_post_code': False, u'code': u'TT', u'name': u'Trinidad And Tobago', u'phone_code': None,
     u'enabled': True, u'slug': u'trinidad-and-tobago'},
    {u'requires_post_code': True, u'code': u'TR', u'name': u'Turkey', u'phone_code': None, u'enabled': True,
     u'slug': u'turkey'},
    {u'requires_post_code': False, u'code': u'TC', u'name': u'Turks And Caicos Islands', u'phone_code': None,
     u'enabled': True, u'slug': u'turks-and-caicos-islands'},
    {u'requires_post_code': True, u'code': u'UA', u'name': u'Ukraine', u'phone_code': None, u'enabled': True,
     u'slug': u'ukraine'},
    {u'requires_post_code': False, u'code': u'AE', u'name': u'United Arab Emirates', u'phone_code': None,
     u'enabled': True, u'slug': u'united-arab-emirates'},
    {u'requires_post_code': True, u'code': u'GB', u'name': u'United Kingdom', u'phone_code': None, u'enabled': True,
     u'slug': u'united-kingdom'},
    {u'requires_post_code': True, u'code': u'US', u'name': u'United States Of America', u'phone_code': None,
     u'enabled': True, u'slug': u'united-states'},
    {u'requires_post_code': False, u'code': u'VA', u'name': u'Vatican City State', u'phone_code': None, u'enabled': True,
     u'slug': u'vatican-city'},
    {u'requires_post_code': False, u'code': u'VG', u'name': u'Virgin Islands (British)', u'phone_code': None,
     u'enabled': True, u'slug': u'british-virgin-islands'},
    {u'requires_post_code': True, u'code': u'LT', u'name': u'Lithuania', u'phone_code': None, u'enabled': True,
     u'slug': u'lithuania'},
    {u'requires_post_code': True, u'code': u'VI', u'name': u'Virgin Islands (Us)', u'phone_code': None,
     u'enabled': True, u'slug': u'u-s-virgin-islands'},
    {u'requires_post_code': False, u'code': u'ZW', u'name': u'Zimbabwe', u'phone_code': None, u'enabled': True,
     u'slug': u'zimbabwe'},
    {u'requires_post_code': True, u'code': u'LU', u'name': u'Luxembourg', u'phone_code': None, u'enabled': True,
     u'slug': u'luxembourg'},
    {u'requires_post_code': False, u'code': u'MO', u'name': u'Macau', u'phone_code': None, u'enabled': True,
     u'slug': u'macau-sar-china'},
    {u'requires_post_code': False, u'code': u'MW', u'name': u'Malawi', u'phone_code': None, u'enabled': True,
     u'slug': u'malawi'},
    {u'requires_post_code': True, u'code': u'YT', u'name': u'Mayotte', u'phone_code': None, u'enabled': True,
     u'slug': u'mayotte'},
    {u'requires_post_code': True, u'code': u'FM', u'name': u'Micronesia, Federated States Of', u'phone_code': None,
     u'enabled': True, u'slug': u'micronesia'},
    {u'requires_post_code': False, u'code': u'AQ', u'name': u'Antarctica', u'phone_code': None, u'enabled': True,
     u'slug': u'antarctica'},
    {u'requires_post_code': False, u'code': u'BL', u'name': u'Saint Barth\xe9lemy', u'phone_code': None,
     u'enabled': True, u'slug': u'saint-barthelemy'},
    {u'requires_post_code': False, u'code': u'BQ', u'name': u'British Antarctic Territory', u'phone_code': None,
     u'enabled': True, u'slug': u'british-antarctic-territory'},
    {u'requires_post_code': True, u'code': u'MA', u'name': u'Morocco', u'phone_code': None, u'enabled': True,
     u'slug': u'morocco'},
    {u'requires_post_code': False, u'code': u'CC', u'name': u'Cocos [Keeling] Islands', u'phone_code': None,
     u'enabled': True, u'slug': u'cocos-keeling-islands'},
    {u'requires_post_code': False, u'code': u'MZ', u'name': u'Mozambique', u'phone_code': None, u'enabled': True,
     u'slug': u'mozambique'},
    {u'requires_post_code': False, u'code': u'EH', u'name': u'Western Sahara', u'phone_code': None, u'enabled': True,
     u'slug': u'western-sahara'},
    {u'requires_post_code': False, u'code': u'AN', u'name': u'Netherlands Antilles', u'phone_code': None,
     u'enabled': False, u'slug': u'netherlands-antilles'},
    {u'requires_post_code': True, u'code': u'PR', u'name': u'Puerto Rico', u'phone_code': None, u'enabled': True,
     u'slug': u'puerto-rico'},
    {u'requires_post_code': False, u'code': u'HM', u'name': u'Heard Island and McDonald Islands', u'phone_code': None,
     u'enabled': True, u'slug': u'heard-island-and-mcdonald-islands'},
    {u'requires_post_code': False, u'code': u'IO', u'name': u'British Indian Ocean Territory', u'phone_code': None,
     u'enabled': True, u'slug': u'british-indian-ocean-territory'},
    {u'requires_post_code': False, u'code': u'QA', u'name': u'Qatar', u'phone_code': None, u'enabled': True,
     u'slug': u'qatar'},
    {u'requires_post_code': False, u'code': u'ST', u'name': u'Sao Tome And Principe', u'phone_code': None,
     u'enabled': True, u'slug': u'sao-tome-and-principe'},
    {u'requires_post_code': False, u'code': u'SA', u'name': u'Saudi Arabia', u'phone_code': None, u'enabled': True,
     u'slug': u'saudi-arabia'},
    {u'requires_post_code': True, u'code': u'RS', u'name': u'Serbia, Republic Of', u'phone_code': None,
     u'enabled': True, u'slug': u'serbia'},
    {u'requires_post_code': False, u'code': u'SC', u'name': u'Seychelles', u'phone_code': None, u'enabled': True,
     u'slug': u'seychelles'},
    {u'requires_post_code': False, u'code': u'LK', u'name': u'Sri Lanka', u'phone_code': None, u'enabled': True,
     u'slug': u'sri-lanka'},
    {u'requires_post_code': False, u'code': u'KN', u'name': u'St. Kitts', u'phone_code': None, u'enabled': True,
     u'slug': u'saint-kitts-and-nevis'},
    {u'requires_post_code': False, u'code': u'VC', u'name': u'St. Vincent', u'phone_code': None, u'enabled': True,
     u'slug': u'saint-vincent-and-the-grenadines'},
    {u'requires_post_code': False, u'code': u'NF', u'name': u'Norfolk Island', u'phone_code': None, u'enabled': True,
     u'slug': u'norfolk-island'},
    {u'requires_post_code': False, u'code': u'PM', u'name': u'Saint Pierre and Miquelon', u'phone_code': None,
     u'enabled': True, u'slug': u'saint-pierre-and-miquelon'},
    {u'requires_post_code': False, u'code': u'SJ', u'name': u'Svalbard and Jan Mayen', u'phone_code': None,
     u'enabled': True, u'slug': u'svalbard-and-jan-mayen'},
    {u'requires_post_code': False, u'code': u'TF', u'name': u'French Southern Territories', u'phone_code': None,
     u'enabled': True, u'slug': u'french-southern-territories'},
    {u'requires_post_code': False, u'code': u'KH', u'name': u'Cambodia', u'phone_code': None, u'enabled': True,
     u'slug': u'cambodia'},
    {u'requires_post_code': False, u'code': u'CM', u'name': u'Cameroon', u'phone_code': None, u'enabled': True,
     u'slug': u'cameroon'},
    {u'requires_post_code': True, u'code': u'CU', u'name': u'Cuba', u'phone_code': None, u'enabled': True,
     u'slug': u'cuba'},
    {u'requires_post_code': True, u'code': u'CY', u'name': u'Cyprus', u'phone_code': None, u'enabled': True,
     u'slug': u'cyprus'},
    {u'requires_post_code': True, u'code': u'CZ', u'name': u'Czech Republic, The', u'phone_code': None,
     u'enabled': True, u'slug': u'czech-republic'},
    {u'requires_post_code': True, u'code': u'DK', u'name': u'Denmark', u'phone_code': None, u'enabled': True,
     u'slug': u'denmark'},
    {u'requires_post_code': False, u'code': u'DJ', u'name': u'Djibouti', u'phone_code': None, u'enabled': True,
     u'slug': u'djibouti'},
    {u'requires_post_code': False, u'code': u'DM', u'name': u'Dominica', u'phone_code': None, u'enabled': True,
     u'slug': u'dominica'},
    {u'requires_post_code': False, u'code': u'DO', u'name': u'Dominican Republic', u'phone_code': None, u'enabled': True,
     u'slug': u'dominican-republic'},
    {u'requires_post_code': False, u'code': u'SV', u'name': u'El Salvador', u'phone_code': None, u'enabled': True,
     u'slug': u'el-salvador'},
    {u'requires_post_code': False, u'code': u'PE', u'name': u'Peru', u'phone_code': None, u'enabled': True,
     u'slug': u'peru'},
    {u'requires_post_code': True, u'code': u'PH', u'name': u'Philippines, The', u'phone_code': None, u'enabled': True,
     u'slug': u'philippines'},
    {u'requires_post_code': True, u'code': u'PL', u'name': u'Poland', u'phone_code': None, u'enabled': True,
     u'slug': u'poland'},
    {u'requires_post_code': True, u'code': u'PT', u'name': u'Portugal', u'phone_code': None, u'enabled': True,
     u'slug': u'portugal'},
    {u'requires_post_code': True, u'code': u'RE', u'name': u'Reunion, Island Of', u'phone_code': None, u'enabled': True,
     u'slug': u'reunion'},
    {u'requires_post_code': True, u'code': u'RO', u'name': u'Romania', u'phone_code': None, u'enabled': True,
     u'slug': u'romania'},
    {u'requires_post_code': True, u'code': u'RU', u'name': u'Russian Federation, The', u'phone_code': None,
     u'enabled': False, u'slug': u'russia'},
    {u'requires_post_code': False, u'code': u'RW', u'name': u'Rwanda', u'phone_code': None, u'enabled': True,
     u'slug': u'rwanda'}], 'klass': 'CountryService'}
